# Site settings
title: Ziyue Wu
SEOTitle: 武子越的博客 | WU ZIYUE's Blog
header-img: img/color20.jpg
email: ziyuewu@zju.edu.cn
description: "Learn By Doing, Keep Your Hands Dirty."
keyword: "Ziyue Wu"
url: "http://Tinky2013.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Tinky2013/Tinky2013.github.io.git" # you code repository

paginate: 10
paginate_path: /blog/page：num

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Continuous learning! Just keep moving!"
sidebar-avatar: /img/photo3.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     tinky2013
github_username:    Tinky2013
facebook_username:  
twitter_username:   ZIYUEWU20




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论
# intensedebate_comments: true
# Disqus（https://disqus.com/）
# disqus_username: tinky2013

# Gitalk
gitalk:
  enable: true #用来做启用判断可以不用
  owner: 'tinky2013' #Github 用户名,
  repo: 'tinky2013.github.io' #储存评论issue的github仓库名
  admin: 'tinky2013' #Github 用户名,
  clientID: 'dbe62285207629cc4e28' #`Github Application clientID`
  clientSecret: '5c80657ef38351c374a9e76e7410eeb1ca1a7323' #`Github Application clientSecret`
  
# gitalk: true
# gitalk_clientID: '035b0b4110249333914a'
# gitalk_Secret: '7e719e0b6475a9231d47535e328352e2062252f6'
# gitalk_repo: 'tinky2013.github.io'
# gitalk_owner: 'tinky2013'
# gitalk_admin: 'tinky2013'
# distractionFreeMode: true


# Analytics settings
# Baidu Analytics
#ba_track_id: xxx

# Google Analytics
#ga_track_id: 'UA-xxxxxxxx-x'       
#ga_domain: xxx.top               # 默认 auto





# Featured Tags
featured-tags: false                    # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
friends: [
    {
        title: "MAO YUHAO",
        href: "https://algebraloveme.github.io/"
    },
    {   
        title: "CHEN XUGAN",
        href: "http://xuganchen.com/"
    },
    {
        title: "YU LINEN",
        href: "https://cestunyu.github.io/"
    },
    {
        title: "LIU YUANJIAN",
        href: "https://www.liuyuanjian.com/"
    }
]
#
